### ISSUE TITLE
The Homapage is not available

### ISSUE THREAD

**Issue by hotchiehGuo** [4DVLab/STCrowd#2]
Is the homepage only be accessed using the campus network of ShanghaiTech? Here I tried the normal network  but it did not work.

**Comment by 4DVLab** [comment]
It may be the DNS is polluted by vpn, you can clear DNS Cache. For mac can refer [this](https://chinese.freecodecamp.org/news/how-to-flush-dns-on-mac-macos-clear-dns-cache/) and for windows just **flushdns**.

**Comment by NeoKH** [comment]
> It may be the DNS is polluted by vpn, you can clear DNS Cache. For mac can refer [this](https://chinese.freecodecamp.org/news/how-to-flush-dns-on-mac-macos-clear-dns-cache/) and for windows just **flushdns**.

I have flushed DNS but it's still unavailable..

**Comment by 4DVLab** [comment]
It seems you have successfully downloaded !

**Comment by hotchiehGuo** [comment]
> It may be the DNS is polluted by vpn, you can clear DNS Cache. For mac can refer [this](https://chinese.freecodecamp.org/news/how-to-flush-dns-on-mac-macos-clear-dns-cache/) and for windows just **flushdns**.

Sorry for not replying your advice in time! Recently I just downloaded the dataset by changing the browser from firefox to google.

**Comment by hotchiehGuo** [comment]
> It seems you have successfully downloaded !

Yeah, it was my fault for not responding and closing this issue in time. Thanks a lot!

**Comment by hotchiehGuo** [comment]
> > It may be the DNS is polluted by vpn, you can clear DNS Cache. For mac can refer [this](https://chinese.freecodecamp.org/news/how-to-flush-dns-on-mac-macos-clear-dns-cache/) and for windows just **flushdns**.
> 
> I have flushed DNS but it's still unavailable.. @4DVLab

I just downloaded the dataset by changing the browser from firefox to google, maybe you can have a try.
