### ISSUE TITLE
Can not access to url

### ISSUE THREAD

**Issue by JiyouSeo** [4DVLab/STCrowd#7]
Thanks for sharing great dataset!

I have a problem with access to dataset [url](http://103.21.143.204:34369/share/EmiZpfjR?diskhost=http://103.21.143.204:53505)..

The error message is occurred like 
```
There is something wrong with the server or the access path does not exist, 
please go back to the main directory and select the access path
```
Can you let me know how to access your dataset url?
Thank you

**Comment by JiyouSeo** [comment]
Problem is solved

**Comment by JiyouSeo** [comment]
I can access url, but download speed is slow.
I guess it is because of network. 
Could you let me know how can I accelerate download speed?

**Comment by 4DVLab** [comment]
We happen to be doing a storage upgrade recently, so it will affect the speed. You can try it again tomorrow (but if it is because of your network, maybe you can try cable ?) or download from our homepage~

**Comment by JiyouSeo** [comment]
Thank you for reply.

In my ubuntu 20.04, I cannot access your homepage [url](http://4dvlab-stcrowd.sist.shanghaitech.edu.cn/), either despite I cleared DNS cache..

**Comment by 4DVLab** [comment]
The dataset has been moved on to google drive!

**Comment by JiyouSeo** [comment]
Thank you !!!!

**Comment by JiyouSeo** [comment]
Thank you for your help!!!!
I have another question..!
Do you have Bird's Eye View Image or Load information about each scenes??

Thank you so much!!
Jiyou Seo

2022년 11월 29일 (화) 오전 3:06, 4DVLab ***@***.***>님이 작성:
